# Experiment Configuration
ExpConfig:
  name: "FGRM"
  experiment: 1
  cudnn_benchmark: True
  seed: 0
  num_epochs: 10
  summary: True
  log: "wandb"      # "wandb"
  device_id: 0   # -1, 1, 2, ...
  task: "segmentation"
  edl_model_path: "./results/EDL_cholecseg8k_dice_evidence_u_1/models/final_model.pt"
  edl_uncertainty: False
# Data configuration
DataConfig:
  name: "cholecseg8k"
  path: "./datasets/cholecseg8k/processed"
  num_classes: 5
  batch_size: 4
  num_workers: 2
# Criterion Configuration
LossConfig:
  name: "policy_gradient"
# Optimizer Configuration
OptimConfig:
  lr: 0.0001
# Scheduler Configuration
SchedulerConfig:
  lr_min: 0.001
  lr_decay_factor: 0.5
  patience: 10
  au_warmup: 10
  num_epochs_lambda: 10
  early_stopping_patience: 10


